//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojoPortal.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_ThongKeTruyCap
    {
        public int ItemID { get; set; }
        public string Type { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> CurrentDay { get; set; }
        public Nullable<int> CurrentWeek { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
    }
}
