//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojoPortal.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_TokenAD
    {
        public long ItemId { get; set; }
        public string access_token { get; set; }
        public string token_type { get; set; }
        public Nullable<int> expires_in { get; set; }
        public string refresh_token { get; set; }
        public string apikey { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_expired { get; set; }
        public string clientId { get; set; }
    }
}
