//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojoPortal.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mp_Roles
    {
        public int RoleID { get; set; }
        public int SiteID { get; set; }
        public string RoleName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.Guid> SiteGuid { get; set; }
        public Nullable<System.Guid> RoleGuid { get; set; }
    
        public virtual mp_Sites mp_Sites { get; set; }
    }
}
