//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrainingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrainingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TrainingResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image now.
        /// </summary>
        internal static string ArticleCurrentImageLabel {
            get {
                return ResourceManager.GetString("ArticleCurrentImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string ArticleEditAuthorLabel {
            get {
                return ResourceManager.GetString("ArticleEditAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string ArticleEditEndDateLabel {
            get {
                return ResourceManager.GetString("ArticleEditEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ArticleEditItemImageUrlLabel {
            get {
                return ResourceManager.GetString("ArticleEditItemImageUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string ArticleEditItemUrlLabel {
            get {
                return ResourceManager.GetString("ArticleEditItemUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chon tìm kiém.
        /// </summary>
        internal static string ArticleEditSearchPropertyLabel {
            get {
                return ResourceManager.GetString("ArticleEditSearchPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string ArticleEditStartDateLabel {
            get {
                return ResourceManager.GetString("ArticleEditStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Training.
        /// </summary>
        internal static string ArticleEditTitleLabel {
            get {
                return ResourceManager.GetString("ArticleEditTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ArticleSearchButton {
            get {
                return ResourceManager.GetString("ArticleSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string ArticleSummaryLabel {
            get {
                return ResourceManager.GetString("ArticleSummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Training.
        /// </summary>
        internal static string BigEventLabel {
            get {
                return ResourceManager.GetString("BigEventLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Training.
        /// </summary>
        internal static string BlogAddPostLabel {
            get {
                return ResourceManager.GetString("BlogAddPostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BlogEditEntryLink {
            get {
                return ResourceManager.GetString("BlogEditEntryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string ButtonAddNew {
            get {
                return ResourceManager.GetString("ButtonAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string ButtonDeleteAll {
            get {
                return ResourceManager.GetString("ButtonDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string ButtonDisabledPleaseWait {
            get {
                return ResourceManager.GetString("ButtonDisabledPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Post.
        /// </summary>
        internal static string DatePost {
            get {
                return ResourceManager.GetString("DatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        internal static string DatetimeTitle {
            get {
                return ResourceManager.GetString("DatetimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this items, are you sure?.
        /// </summary>
        internal static string DeleteAllConfirmWarning {
            get {
                return ResourceManager.GetString("DeleteAllConfirmWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item, are you sure?.
        /// </summary>
        internal static string DeleteConfirmWarning {
            get {
                return ResourceManager.GetString("DeleteConfirmWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string HeaderArticleTitle {
            get {
                return ResourceManager.GetString("HeaderArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string IsPublishedLabel {
            get {
                return ResourceManager.GetString("IsPublishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orther Training.
        /// </summary>
        internal static string OrtherTraining {
            get {
                return ResourceManager.GetString("OrtherTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the begin date..
        /// </summary>
        internal static string ParseDateFailureMessage {
            get {
                return ResourceManager.GetString("ParseDateFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string PlaceLabel {
            get {
                return ResourceManager.GetString("PlaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string PlaceTitle {
            get {
                return ResourceManager.GetString("PlaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post List.
        /// </summary>
        internal static string PostList {
            get {
                return ResourceManager.GetString("PostList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string PublishedTilte {
            get {
                return ResourceManager.GetString("PublishedTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Training.
        /// </summary>
        internal static string TimeTrainging {
            get {
                return ResourceManager.GetString("TimeTrainging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1:Publish Status,2:Non publish,1:Published,0:UnPublished.
        /// </summary>
        internal static string TrainingPublishStatus {
            get {
                return ResourceManager.GetString("TrainingPublishStatus", resourceCulture);
            }
        }
    }
}
