#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojoPortal.Features.Business.SwirlingQuestion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eAitaPortal")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmp_Module(mp_Module instance);
    partial void Updatemp_Module(mp_Module instance);
    partial void Deletemp_Module(mp_Module instance);
    partial void Insertud_QAComment(ud_QAComment instance);
    partial void Updateud_QAComment(ud_QAComment instance);
    partial void Deleteud_QAComment(ud_QAComment instance);
    partial void Insertmd_QA(md_QA instance);
    partial void Updatemd_QA(md_QA instance);
    partial void Deletemd_QA(md_QA instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::mojoPortal.Features.Business.Properties.Settings.Default.eAitaPortalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mp_Module> mp_Modules
		{
			get
			{
				return this.GetTable<mp_Module>();
			}
		}
		
		public System.Data.Linq.Table<ud_QAComment> ud_QAComments
		{
			get
			{
				return this.GetTable<ud_QAComment>();
			}
		}
		
		public System.Data.Linq.Table<md_QA> md_QAs
		{
			get
			{
				return this.GetTable<md_QA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mp_Modules")]
	public partial class mp_Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModuleID;
		
		private System.Nullable<int> _SiteID;
		
		private int _ModuleDefID;
		
		private string _ModuleTitle;
		
		private string _AuthorizedEditRoles;
		
		private int _CacheTime;
		
		private System.Nullable<bool> _ShowTitle;
		
		private int _EditUserID;
		
		private bool _AvailableForMyPage;
		
		private bool _AllowMultipleInstancesOnMyPage;
		
		private string _Icon;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private int _CountOfUseOnMyPage;
		
		private System.Nullable<System.Guid> _Guid;
		
		private System.Nullable<System.Guid> _FeatureGuid;
		
		private System.Nullable<System.Guid> _SiteGuid;
		
		private System.Nullable<System.Guid> _EditUserGuid;
		
		private bool _HideFromUnAuth;
		
		private bool _HideFromAuth;
		
		private string _ViewRoles;
		
		private string _DraftEditRoles;
		
		private System.Nullable<bool> _IncludeInSearch;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModuleIDChanging(int value);
    partial void OnModuleIDChanged();
    partial void OnSiteIDChanging(System.Nullable<int> value);
    partial void OnSiteIDChanged();
    partial void OnModuleDefIDChanging(int value);
    partial void OnModuleDefIDChanged();
    partial void OnModuleTitleChanging(string value);
    partial void OnModuleTitleChanged();
    partial void OnAuthorizedEditRolesChanging(string value);
    partial void OnAuthorizedEditRolesChanged();
    partial void OnCacheTimeChanging(int value);
    partial void OnCacheTimeChanged();
    partial void OnShowTitleChanging(System.Nullable<bool> value);
    partial void OnShowTitleChanged();
    partial void OnEditUserIDChanging(int value);
    partial void OnEditUserIDChanged();
    partial void OnAvailableForMyPageChanging(bool value);
    partial void OnAvailableForMyPageChanged();
    partial void OnAllowMultipleInstancesOnMyPageChanging(bool value);
    partial void OnAllowMultipleInstancesOnMyPageChanged();
    partial void OnIconChanging(string value);
    partial void OnIconChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnCountOfUseOnMyPageChanging(int value);
    partial void OnCountOfUseOnMyPageChanged();
    partial void OnGuidChanging(System.Nullable<System.Guid> value);
    partial void OnGuidChanged();
    partial void OnFeatureGuidChanging(System.Nullable<System.Guid> value);
    partial void OnFeatureGuidChanged();
    partial void OnSiteGuidChanging(System.Nullable<System.Guid> value);
    partial void OnSiteGuidChanged();
    partial void OnEditUserGuidChanging(System.Nullable<System.Guid> value);
    partial void OnEditUserGuidChanged();
    partial void OnHideFromUnAuthChanging(bool value);
    partial void OnHideFromUnAuthChanged();
    partial void OnHideFromAuthChanging(bool value);
    partial void OnHideFromAuthChanged();
    partial void OnViewRolesChanging(string value);
    partial void OnViewRolesChanged();
    partial void OnDraftEditRolesChanging(string value);
    partial void OnDraftEditRolesChanged();
    partial void OnIncludeInSearchChanging(System.Nullable<bool> value);
    partial void OnIncludeInSearchChanged();
    #endregion
		
		public mp_Module()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="Int")]
		public System.Nullable<int> SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleDefID", DbType="Int NOT NULL")]
		public int ModuleDefID
		{
			get
			{
				return this._ModuleDefID;
			}
			set
			{
				if ((this._ModuleDefID != value))
				{
					this.OnModuleDefIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleDefID = value;
					this.SendPropertyChanged("ModuleDefID");
					this.OnModuleDefIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleTitle", DbType="NVarChar(255)")]
		public string ModuleTitle
		{
			get
			{
				return this._ModuleTitle;
			}
			set
			{
				if ((this._ModuleTitle != value))
				{
					this.OnModuleTitleChanging(value);
					this.SendPropertyChanging();
					this._ModuleTitle = value;
					this.SendPropertyChanged("ModuleTitle");
					this.OnModuleTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizedEditRoles", DbType="NVarChar(MAX)")]
		public string AuthorizedEditRoles
		{
			get
			{
				return this._AuthorizedEditRoles;
			}
			set
			{
				if ((this._AuthorizedEditRoles != value))
				{
					this.OnAuthorizedEditRolesChanging(value);
					this.SendPropertyChanging();
					this._AuthorizedEditRoles = value;
					this.SendPropertyChanged("AuthorizedEditRoles");
					this.OnAuthorizedEditRolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CacheTime", DbType="Int NOT NULL")]
		public int CacheTime
		{
			get
			{
				return this._CacheTime;
			}
			set
			{
				if ((this._CacheTime != value))
				{
					this.OnCacheTimeChanging(value);
					this.SendPropertyChanging();
					this._CacheTime = value;
					this.SendPropertyChanged("CacheTime");
					this.OnCacheTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTitle", DbType="Bit")]
		public System.Nullable<bool> ShowTitle
		{
			get
			{
				return this._ShowTitle;
			}
			set
			{
				if ((this._ShowTitle != value))
				{
					this.OnShowTitleChanging(value);
					this.SendPropertyChanging();
					this._ShowTitle = value;
					this.SendPropertyChanged("ShowTitle");
					this.OnShowTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUserID", DbType="Int NOT NULL")]
		public int EditUserID
		{
			get
			{
				return this._EditUserID;
			}
			set
			{
				if ((this._EditUserID != value))
				{
					this.OnEditUserIDChanging(value);
					this.SendPropertyChanging();
					this._EditUserID = value;
					this.SendPropertyChanged("EditUserID");
					this.OnEditUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableForMyPage", DbType="Bit NOT NULL")]
		public bool AvailableForMyPage
		{
			get
			{
				return this._AvailableForMyPage;
			}
			set
			{
				if ((this._AvailableForMyPage != value))
				{
					this.OnAvailableForMyPageChanging(value);
					this.SendPropertyChanging();
					this._AvailableForMyPage = value;
					this.SendPropertyChanged("AvailableForMyPage");
					this.OnAvailableForMyPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowMultipleInstancesOnMyPage", DbType="Bit NOT NULL")]
		public bool AllowMultipleInstancesOnMyPage
		{
			get
			{
				return this._AllowMultipleInstancesOnMyPage;
			}
			set
			{
				if ((this._AllowMultipleInstancesOnMyPage != value))
				{
					this.OnAllowMultipleInstancesOnMyPageChanging(value);
					this.SendPropertyChanging();
					this._AllowMultipleInstancesOnMyPage = value;
					this.SendPropertyChanged("AllowMultipleInstancesOnMyPage");
					this.OnAllowMultipleInstancesOnMyPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(255)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this.OnIconChanging(value);
					this.SendPropertyChanging();
					this._Icon = value;
					this.SendPropertyChanged("Icon");
					this.OnIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountOfUseOnMyPage", DbType="Int NOT NULL")]
		public int CountOfUseOnMyPage
		{
			get
			{
				return this._CountOfUseOnMyPage;
			}
			set
			{
				if ((this._CountOfUseOnMyPage != value))
				{
					this.OnCountOfUseOnMyPageChanging(value);
					this.SendPropertyChanging();
					this._CountOfUseOnMyPage = value;
					this.SendPropertyChanged("CountOfUseOnMyPage");
					this.OnCountOfUseOnMyPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Guid
		{
			get
			{
				return this._Guid;
			}
			set
			{
				if ((this._Guid != value))
				{
					this.OnGuidChanging(value);
					this.SendPropertyChanging();
					this._Guid = value;
					this.SendPropertyChanged("Guid");
					this.OnGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeatureGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> FeatureGuid
		{
			get
			{
				return this._FeatureGuid;
			}
			set
			{
				if ((this._FeatureGuid != value))
				{
					this.OnFeatureGuidChanging(value);
					this.SendPropertyChanging();
					this._FeatureGuid = value;
					this.SendPropertyChanged("FeatureGuid");
					this.OnFeatureGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SiteGuid
		{
			get
			{
				return this._SiteGuid;
			}
			set
			{
				if ((this._SiteGuid != value))
				{
					this.OnSiteGuidChanging(value);
					this.SendPropertyChanging();
					this._SiteGuid = value;
					this.SendPropertyChanged("SiteGuid");
					this.OnSiteGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUserGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> EditUserGuid
		{
			get
			{
				return this._EditUserGuid;
			}
			set
			{
				if ((this._EditUserGuid != value))
				{
					this.OnEditUserGuidChanging(value);
					this.SendPropertyChanging();
					this._EditUserGuid = value;
					this.SendPropertyChanged("EditUserGuid");
					this.OnEditUserGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HideFromUnAuth", DbType="Bit NOT NULL")]
		public bool HideFromUnAuth
		{
			get
			{
				return this._HideFromUnAuth;
			}
			set
			{
				if ((this._HideFromUnAuth != value))
				{
					this.OnHideFromUnAuthChanging(value);
					this.SendPropertyChanging();
					this._HideFromUnAuth = value;
					this.SendPropertyChanged("HideFromUnAuth");
					this.OnHideFromUnAuthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HideFromAuth", DbType="Bit NOT NULL")]
		public bool HideFromAuth
		{
			get
			{
				return this._HideFromAuth;
			}
			set
			{
				if ((this._HideFromAuth != value))
				{
					this.OnHideFromAuthChanging(value);
					this.SendPropertyChanging();
					this._HideFromAuth = value;
					this.SendPropertyChanged("HideFromAuth");
					this.OnHideFromAuthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewRoles", DbType="NVarChar(MAX)")]
		public string ViewRoles
		{
			get
			{
				return this._ViewRoles;
			}
			set
			{
				if ((this._ViewRoles != value))
				{
					this.OnViewRolesChanging(value);
					this.SendPropertyChanging();
					this._ViewRoles = value;
					this.SendPropertyChanged("ViewRoles");
					this.OnViewRolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DraftEditRoles", DbType="NVarChar(MAX)")]
		public string DraftEditRoles
		{
			get
			{
				return this._DraftEditRoles;
			}
			set
			{
				if ((this._DraftEditRoles != value))
				{
					this.OnDraftEditRolesChanging(value);
					this.SendPropertyChanging();
					this._DraftEditRoles = value;
					this.SendPropertyChanged("DraftEditRoles");
					this.OnDraftEditRolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncludeInSearch", DbType="Bit")]
		public System.Nullable<bool> IncludeInSearch
		{
			get
			{
				return this._IncludeInSearch;
			}
			set
			{
				if ((this._IncludeInSearch != value))
				{
					this.OnIncludeInSearchChanging(value);
					this.SendPropertyChanging();
					this._IncludeInSearch = value;
					this.SendPropertyChanged("IncludeInSearch");
					this.OnIncludeInSearchChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.md_QAComments")]
	public partial class ud_QAComment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Guid;
		
		private int _ModuleID;
		
		private System.Guid _QAGuid;
		
		private string _Title;
		
		private string _Name;
		
		private string _Email;
		
		private string _Comment;
		
		private System.DateTime _CreatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGuidChanging(System.Guid value);
    partial void OnGuidChanged();
    partial void OnModuleIDChanging(int value);
    partial void OnModuleIDChanged();
    partial void OnQAGuidChanging(System.Guid value);
    partial void OnQAGuidChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    #endregion
		
		public ud_QAComment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Guid
		{
			get
			{
				return this._Guid;
			}
			set
			{
				if ((this._Guid != value))
				{
					this.OnGuidChanging(value);
					this.SendPropertyChanging();
					this._Guid = value;
					this.SendPropertyChanged("Guid");
					this.OnGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", DbType="Int NOT NULL")]
		public int ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QAGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid QAGuid
		{
			get
			{
				return this._QAGuid;
			}
			set
			{
				if ((this._QAGuid != value))
				{
					this.OnQAGuidChanging(value);
					this.SendPropertyChanging();
					this._QAGuid = value;
					this.SendPropertyChanged("QAGuid");
					this.OnQAGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.md_QA")]
	public partial class md_QA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Guid;
		
		private int _ModuleID;
		
		private string _Title;
		
		private string _Question;
		
		private string _Answer;
		
		private bool _IsPublished;
		
		private System.DateTime _LastModified;
		
		private string _CreatedByName;
		
		private string _CreatedByEmail;
		
		private string _CreatedByPhone;
		
		private System.Nullable<int> _AnswerUser;
		
		private int _HitCount;
		
		private string _ItemUrl;
		
		private System.Nullable<bool> _IsHot;
		
		private int _CommentCount;
		
		private System.Nullable<int> _QACategoryID;
		
		private System.Nullable<int> _CoQuanID;
		
		private System.Nullable<bool> _Is_Active;
		
		private string _LyDoXoa;
		
		private System.Nullable<bool> _ViPhamQuyChe;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _DuyetCauHoi;
		
		private System.Nullable<bool> _DuThaoTraLoi;
		
		private string _FileDinhKem;
		
		private System.Nullable<bool> _DuyetDuThaoTraLoi;
		
		private string _LyDoKhongPheDuyetTraLoi;
		
		private System.Nullable<bool> _XuatBanDuThaoTraLoi;
		
		private System.Nullable<System.Guid> _NguoiXoaCauHoi;
		
		private System.Nullable<System.Guid> _NguoiKiemDuyet;
		
		private System.Nullable<System.DateTime> _NgayXoaCauHoi;
		
		private System.Nullable<System.DateTime> _NgayKiemDuyet;
		
		private System.Nullable<System.Guid> _NguoiXuatBanCauHoi;
		
		private System.Nullable<System.DateTime> _NgayXuatBanCauHoi;
		
		private System.Nullable<System.Guid> _NguoiTaoDuThaoTraLoi;
		
		private System.Nullable<System.DateTime> _NgayTaoDuThao;
		
		private System.Nullable<System.Guid> _NguoiPheDuyetDuThao;
		
		private System.Nullable<System.DateTime> _NgayPheDuyet;
		
		private System.Nullable<System.Guid> _NguoiXuatBanCauTraLoi;
		
		private System.Nullable<System.DateTime> _NgayXuatBanCauTraLoi;
		
		private System.Nullable<bool> _TiepNhanCauHoi;
		
		private string _FTS;
		
		private System.Nullable<bool> _KhongPheDuyetTraLoi;
		
		private System.Nullable<int> _PhongBanID;
		
		private System.Nullable<bool> _DuyetThongBao;
		
		private System.Nullable<System.Guid> _NguoiDuyetThongBao;
		
		private System.Nullable<System.DateTime> _NgayDuyetThongBao;
		
		private System.Nullable<bool> _XuatBanThongBao;
		
		private System.Nullable<System.Guid> _NguoiXuatBanThongBao;
		
		private System.Nullable<System.DateTime> _NgayXuatBanThongBao;
		
		private System.Nullable<int> _CreatQuestionByUser;
		
		private System.Nullable<System.DateTime> _NgayTiepNhan;
		
		private System.Nullable<int> _NguoiTiepNhan;
		
		private System.Nullable<bool> _StatusSend;
		
		private System.Nullable<bool> _ChuyenDuThao;
		
		private System.Nullable<int> _NguoiChuyenDuThao;
		
		private System.Nullable<System.DateTime> _NgayChuyenDuThao;
		
		private int _SiteID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGuidChanging(System.Guid value);
    partial void OnGuidChanged();
    partial void OnModuleIDChanging(int value);
    partial void OnModuleIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    partial void OnIsPublishedChanging(bool value);
    partial void OnIsPublishedChanged();
    partial void OnLastModifiedChanging(System.DateTime value);
    partial void OnLastModifiedChanged();
    partial void OnCreatedByNameChanging(string value);
    partial void OnCreatedByNameChanged();
    partial void OnCreatedByEmailChanging(string value);
    partial void OnCreatedByEmailChanged();
    partial void OnCreatedByPhoneChanging(string value);
    partial void OnCreatedByPhoneChanged();
    partial void OnAnswerUserChanging(System.Nullable<int> value);
    partial void OnAnswerUserChanged();
    partial void OnHitCountChanging(int value);
    partial void OnHitCountChanged();
    partial void OnItemUrlChanging(string value);
    partial void OnItemUrlChanged();
    partial void OnIsHotChanging(System.Nullable<bool> value);
    partial void OnIsHotChanged();
    partial void OnCommentCountChanging(int value);
    partial void OnCommentCountChanged();
    partial void OnQACategoryIDChanging(System.Nullable<int> value);
    partial void OnQACategoryIDChanged();
    partial void OnCoQuanIDChanging(System.Nullable<int> value);
    partial void OnCoQuanIDChanged();
    partial void OnIs_ActiveChanging(System.Nullable<bool> value);
    partial void OnIs_ActiveChanged();
    partial void OnLyDoXoaChanging(string value);
    partial void OnLyDoXoaChanged();
    partial void OnViPhamQuyCheChanging(System.Nullable<bool> value);
    partial void OnViPhamQuyCheChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnDuyetCauHoiChanging(System.Nullable<bool> value);
    partial void OnDuyetCauHoiChanged();
    partial void OnDuThaoTraLoiChanging(System.Nullable<bool> value);
    partial void OnDuThaoTraLoiChanged();
    partial void OnFileDinhKemChanging(string value);
    partial void OnFileDinhKemChanged();
    partial void OnDuyetDuThaoTraLoiChanging(System.Nullable<bool> value);
    partial void OnDuyetDuThaoTraLoiChanged();
    partial void OnLyDoKhongPheDuyetTraLoiChanging(string value);
    partial void OnLyDoKhongPheDuyetTraLoiChanged();
    partial void OnXuatBanDuThaoTraLoiChanging(System.Nullable<bool> value);
    partial void OnXuatBanDuThaoTraLoiChanged();
    partial void OnNguoiXoaCauHoiChanging(System.Nullable<System.Guid> value);
    partial void OnNguoiXoaCauHoiChanged();
    partial void OnNguoiKiemDuyetChanging(System.Nullable<System.Guid> value);
    partial void OnNguoiKiemDuyetChanged();
    partial void OnNgayXoaCauHoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXoaCauHoiChanged();
    partial void OnNgayKiemDuyetChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKiemDuyetChanged();
    partial void OnNguoiXuatBanCauHoiChanging(System.Nullable<System.Guid> value);
    partial void OnNguoiXuatBanCauHoiChanged();
    partial void OnNgayXuatBanCauHoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuatBanCauHoiChanged();
    partial void OnNguoiTaoDuThaoTraLoiChanging(System.Nullable<System.Guid> value);
    partial void OnNguoiTaoDuThaoTraLoiChanged();
    partial void OnNgayTaoDuThaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoDuThaoChanged();
    partial void OnNguoiPheDuyetDuThaoChanging(System.Nullable<System.Guid> value);
    partial void OnNguoiPheDuyetDuThaoChanged();
    partial void OnNgayPheDuyetChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayPheDuyetChanged();
    partial void OnNguoiXuatBanCauTraLoiChanging(System.Nullable<System.Guid> value);
    partial void OnNguoiXuatBanCauTraLoiChanged();
    partial void OnNgayXuatBanCauTraLoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuatBanCauTraLoiChanged();
    partial void OnTiepNhanCauHoiChanging(System.Nullable<bool> value);
    partial void OnTiepNhanCauHoiChanged();
    partial void OnFTSChanging(string value);
    partial void OnFTSChanged();
    partial void OnKhongPheDuyetTraLoiChanging(System.Nullable<bool> value);
    partial void OnKhongPheDuyetTraLoiChanged();
    partial void OnPhongBanIDChanging(System.Nullable<int> value);
    partial void OnPhongBanIDChanged();
    partial void OnDuyetThongBaoChanging(System.Nullable<bool> value);
    partial void OnDuyetThongBaoChanged();
    partial void OnNguoiDuyetThongBaoChanging(System.Nullable<System.Guid> value);
    partial void OnNguoiDuyetThongBaoChanged();
    partial void OnNgayDuyetThongBaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDuyetThongBaoChanged();
    partial void OnXuatBanThongBaoChanging(System.Nullable<bool> value);
    partial void OnXuatBanThongBaoChanged();
    partial void OnNguoiXuatBanThongBaoChanging(System.Nullable<System.Guid> value);
    partial void OnNguoiXuatBanThongBaoChanged();
    partial void OnNgayXuatBanThongBaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuatBanThongBaoChanged();
    partial void OnCreatQuestionByUserChanging(System.Nullable<int> value);
    partial void OnCreatQuestionByUserChanged();
    partial void OnNgayTiepNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTiepNhanChanged();
    partial void OnNguoiTiepNhanChanging(System.Nullable<int> value);
    partial void OnNguoiTiepNhanChanged();
    partial void OnStatusSendChanging(System.Nullable<bool> value);
    partial void OnStatusSendChanged();
    partial void OnChuyenDuThaoChanging(System.Nullable<bool> value);
    partial void OnChuyenDuThaoChanged();
    partial void OnNguoiChuyenDuThaoChanging(System.Nullable<int> value);
    partial void OnNguoiChuyenDuThaoChanged();
    partial void OnNgayChuyenDuThaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenDuThaoChanged();
    partial void OnSiteIDChanging(int value);
    partial void OnSiteIDChanged();
    #endregion
		
		public md_QA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Guid
		{
			get
			{
				return this._Guid;
			}
			set
			{
				if ((this._Guid != value))
				{
					this.OnGuidChanging(value);
					this.SendPropertyChanging();
					this._Guid = value;
					this.SendPropertyChanged("Guid");
					this.OnGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", DbType="Int NOT NULL")]
		public int ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(MAX)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this.OnIsPublishedChanging(value);
					this.SendPropertyChanging();
					this._IsPublished = value;
					this.SendPropertyChanged("IsPublished");
					this.OnIsPublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModified", DbType="DateTime NOT NULL")]
		public System.DateTime LastModified
		{
			get
			{
				return this._LastModified;
			}
			set
			{
				if ((this._LastModified != value))
				{
					this.OnLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._LastModified = value;
					this.SendPropertyChanged("LastModified");
					this.OnLastModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByName", DbType="NVarChar(255)")]
		public string CreatedByName
		{
			get
			{
				return this._CreatedByName;
			}
			set
			{
				if ((this._CreatedByName != value))
				{
					this.OnCreatedByNameChanging(value);
					this.SendPropertyChanging();
					this._CreatedByName = value;
					this.SendPropertyChanged("CreatedByName");
					this.OnCreatedByNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByEmail", DbType="NVarChar(255)")]
		public string CreatedByEmail
		{
			get
			{
				return this._CreatedByEmail;
			}
			set
			{
				if ((this._CreatedByEmail != value))
				{
					this.OnCreatedByEmailChanging(value);
					this.SendPropertyChanging();
					this._CreatedByEmail = value;
					this.SendPropertyChanged("CreatedByEmail");
					this.OnCreatedByEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByPhone", DbType="NVarChar(50)")]
		public string CreatedByPhone
		{
			get
			{
				return this._CreatedByPhone;
			}
			set
			{
				if ((this._CreatedByPhone != value))
				{
					this.OnCreatedByPhoneChanging(value);
					this.SendPropertyChanging();
					this._CreatedByPhone = value;
					this.SendPropertyChanged("CreatedByPhone");
					this.OnCreatedByPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerUser", DbType="Int")]
		public System.Nullable<int> AnswerUser
		{
			get
			{
				return this._AnswerUser;
			}
			set
			{
				if ((this._AnswerUser != value))
				{
					this.OnAnswerUserChanging(value);
					this.SendPropertyChanging();
					this._AnswerUser = value;
					this.SendPropertyChanged("AnswerUser");
					this.OnAnswerUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HitCount", DbType="Int NOT NULL")]
		public int HitCount
		{
			get
			{
				return this._HitCount;
			}
			set
			{
				if ((this._HitCount != value))
				{
					this.OnHitCountChanging(value);
					this.SendPropertyChanging();
					this._HitCount = value;
					this.SendPropertyChanged("HitCount");
					this.OnHitCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemUrl", DbType="NVarChar(255)")]
		public string ItemUrl
		{
			get
			{
				return this._ItemUrl;
			}
			set
			{
				if ((this._ItemUrl != value))
				{
					this.OnItemUrlChanging(value);
					this.SendPropertyChanging();
					this._ItemUrl = value;
					this.SendPropertyChanged("ItemUrl");
					this.OnItemUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHot", DbType="Bit")]
		public System.Nullable<bool> IsHot
		{
			get
			{
				return this._IsHot;
			}
			set
			{
				if ((this._IsHot != value))
				{
					this.OnIsHotChanging(value);
					this.SendPropertyChanging();
					this._IsHot = value;
					this.SendPropertyChanged("IsHot");
					this.OnIsHotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentCount", DbType="Int NOT NULL")]
		public int CommentCount
		{
			get
			{
				return this._CommentCount;
			}
			set
			{
				if ((this._CommentCount != value))
				{
					this.OnCommentCountChanging(value);
					this.SendPropertyChanging();
					this._CommentCount = value;
					this.SendPropertyChanged("CommentCount");
					this.OnCommentCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QACategoryID", DbType="Int")]
		public System.Nullable<int> QACategoryID
		{
			get
			{
				return this._QACategoryID;
			}
			set
			{
				if ((this._QACategoryID != value))
				{
					this.OnQACategoryIDChanging(value);
					this.SendPropertyChanging();
					this._QACategoryID = value;
					this.SendPropertyChanged("QACategoryID");
					this.OnQACategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuanID", DbType="Int")]
		public System.Nullable<int> CoQuanID
		{
			get
			{
				return this._CoQuanID;
			}
			set
			{
				if ((this._CoQuanID != value))
				{
					this.OnCoQuanIDChanging(value);
					this.SendPropertyChanging();
					this._CoQuanID = value;
					this.SendPropertyChanged("CoQuanID");
					this.OnCoQuanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Active", DbType="Bit")]
		public System.Nullable<bool> Is_Active
		{
			get
			{
				return this._Is_Active;
			}
			set
			{
				if ((this._Is_Active != value))
				{
					this.OnIs_ActiveChanging(value);
					this.SendPropertyChanging();
					this._Is_Active = value;
					this.SendPropertyChanged("Is_Active");
					this.OnIs_ActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDoXoa", DbType="NVarChar(MAX)")]
		public string LyDoXoa
		{
			get
			{
				return this._LyDoXoa;
			}
			set
			{
				if ((this._LyDoXoa != value))
				{
					this.OnLyDoXoaChanging(value);
					this.SendPropertyChanging();
					this._LyDoXoa = value;
					this.SendPropertyChanged("LyDoXoa");
					this.OnLyDoXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViPhamQuyChe", DbType="Bit")]
		public System.Nullable<bool> ViPhamQuyChe
		{
			get
			{
				return this._ViPhamQuyChe;
			}
			set
			{
				if ((this._ViPhamQuyChe != value))
				{
					this.OnViPhamQuyCheChanging(value);
					this.SendPropertyChanging();
					this._ViPhamQuyChe = value;
					this.SendPropertyChanged("ViPhamQuyChe");
					this.OnViPhamQuyCheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuyetCauHoi", DbType="Bit")]
		public System.Nullable<bool> DuyetCauHoi
		{
			get
			{
				return this._DuyetCauHoi;
			}
			set
			{
				if ((this._DuyetCauHoi != value))
				{
					this.OnDuyetCauHoiChanging(value);
					this.SendPropertyChanging();
					this._DuyetCauHoi = value;
					this.SendPropertyChanged("DuyetCauHoi");
					this.OnDuyetCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuThaoTraLoi", DbType="Bit")]
		public System.Nullable<bool> DuThaoTraLoi
		{
			get
			{
				return this._DuThaoTraLoi;
			}
			set
			{
				if ((this._DuThaoTraLoi != value))
				{
					this.OnDuThaoTraLoiChanging(value);
					this.SendPropertyChanging();
					this._DuThaoTraLoi = value;
					this.SendPropertyChanged("DuThaoTraLoi");
					this.OnDuThaoTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(255)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this.OnFileDinhKemChanging(value);
					this.SendPropertyChanging();
					this._FileDinhKem = value;
					this.SendPropertyChanged("FileDinhKem");
					this.OnFileDinhKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuyetDuThaoTraLoi", DbType="Bit")]
		public System.Nullable<bool> DuyetDuThaoTraLoi
		{
			get
			{
				return this._DuyetDuThaoTraLoi;
			}
			set
			{
				if ((this._DuyetDuThaoTraLoi != value))
				{
					this.OnDuyetDuThaoTraLoiChanging(value);
					this.SendPropertyChanging();
					this._DuyetDuThaoTraLoi = value;
					this.SendPropertyChanged("DuyetDuThaoTraLoi");
					this.OnDuyetDuThaoTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDoKhongPheDuyetTraLoi", DbType="NVarChar(MAX)")]
		public string LyDoKhongPheDuyetTraLoi
		{
			get
			{
				return this._LyDoKhongPheDuyetTraLoi;
			}
			set
			{
				if ((this._LyDoKhongPheDuyetTraLoi != value))
				{
					this.OnLyDoKhongPheDuyetTraLoiChanging(value);
					this.SendPropertyChanging();
					this._LyDoKhongPheDuyetTraLoi = value;
					this.SendPropertyChanged("LyDoKhongPheDuyetTraLoi");
					this.OnLyDoKhongPheDuyetTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatBanDuThaoTraLoi", DbType="Bit")]
		public System.Nullable<bool> XuatBanDuThaoTraLoi
		{
			get
			{
				return this._XuatBanDuThaoTraLoi;
			}
			set
			{
				if ((this._XuatBanDuThaoTraLoi != value))
				{
					this.OnXuatBanDuThaoTraLoiChanging(value);
					this.SendPropertyChanging();
					this._XuatBanDuThaoTraLoi = value;
					this.SendPropertyChanged("XuatBanDuThaoTraLoi");
					this.OnXuatBanDuThaoTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiXoaCauHoi", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiXoaCauHoi
		{
			get
			{
				return this._NguoiXoaCauHoi;
			}
			set
			{
				if ((this._NguoiXoaCauHoi != value))
				{
					this.OnNguoiXoaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._NguoiXoaCauHoi = value;
					this.SendPropertyChanged("NguoiXoaCauHoi");
					this.OnNguoiXoaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiKiemDuyet", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiKiemDuyet
		{
			get
			{
				return this._NguoiKiemDuyet;
			}
			set
			{
				if ((this._NguoiKiemDuyet != value))
				{
					this.OnNguoiKiemDuyetChanging(value);
					this.SendPropertyChanging();
					this._NguoiKiemDuyet = value;
					this.SendPropertyChanged("NguoiKiemDuyet");
					this.OnNguoiKiemDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXoaCauHoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXoaCauHoi
		{
			get
			{
				return this._NgayXoaCauHoi;
			}
			set
			{
				if ((this._NgayXoaCauHoi != value))
				{
					this.OnNgayXoaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._NgayXoaCauHoi = value;
					this.SendPropertyChanged("NgayXoaCauHoi");
					this.OnNgayXoaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKiemDuyet", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKiemDuyet
		{
			get
			{
				return this._NgayKiemDuyet;
			}
			set
			{
				if ((this._NgayKiemDuyet != value))
				{
					this.OnNgayKiemDuyetChanging(value);
					this.SendPropertyChanging();
					this._NgayKiemDuyet = value;
					this.SendPropertyChanged("NgayKiemDuyet");
					this.OnNgayKiemDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiXuatBanCauHoi", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiXuatBanCauHoi
		{
			get
			{
				return this._NguoiXuatBanCauHoi;
			}
			set
			{
				if ((this._NguoiXuatBanCauHoi != value))
				{
					this.OnNguoiXuatBanCauHoiChanging(value);
					this.SendPropertyChanging();
					this._NguoiXuatBanCauHoi = value;
					this.SendPropertyChanged("NguoiXuatBanCauHoi");
					this.OnNguoiXuatBanCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuatBanCauHoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXuatBanCauHoi
		{
			get
			{
				return this._NgayXuatBanCauHoi;
			}
			set
			{
				if ((this._NgayXuatBanCauHoi != value))
				{
					this.OnNgayXuatBanCauHoiChanging(value);
					this.SendPropertyChanging();
					this._NgayXuatBanCauHoi = value;
					this.SendPropertyChanged("NgayXuatBanCauHoi");
					this.OnNgayXuatBanCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTaoDuThaoTraLoi", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiTaoDuThaoTraLoi
		{
			get
			{
				return this._NguoiTaoDuThaoTraLoi;
			}
			set
			{
				if ((this._NguoiTaoDuThaoTraLoi != value))
				{
					this.OnNguoiTaoDuThaoTraLoiChanging(value);
					this.SendPropertyChanging();
					this._NguoiTaoDuThaoTraLoi = value;
					this.SendPropertyChanged("NguoiTaoDuThaoTraLoi");
					this.OnNguoiTaoDuThaoTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTaoDuThao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTaoDuThao
		{
			get
			{
				return this._NgayTaoDuThao;
			}
			set
			{
				if ((this._NgayTaoDuThao != value))
				{
					this.OnNgayTaoDuThaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTaoDuThao = value;
					this.SendPropertyChanged("NgayTaoDuThao");
					this.OnNgayTaoDuThaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiPheDuyetDuThao", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiPheDuyetDuThao
		{
			get
			{
				return this._NguoiPheDuyetDuThao;
			}
			set
			{
				if ((this._NguoiPheDuyetDuThao != value))
				{
					this.OnNguoiPheDuyetDuThaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiPheDuyetDuThao = value;
					this.SendPropertyChanged("NguoiPheDuyetDuThao");
					this.OnNguoiPheDuyetDuThaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPheDuyet", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayPheDuyet
		{
			get
			{
				return this._NgayPheDuyet;
			}
			set
			{
				if ((this._NgayPheDuyet != value))
				{
					this.OnNgayPheDuyetChanging(value);
					this.SendPropertyChanging();
					this._NgayPheDuyet = value;
					this.SendPropertyChanged("NgayPheDuyet");
					this.OnNgayPheDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiXuatBanCauTraLoi", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiXuatBanCauTraLoi
		{
			get
			{
				return this._NguoiXuatBanCauTraLoi;
			}
			set
			{
				if ((this._NguoiXuatBanCauTraLoi != value))
				{
					this.OnNguoiXuatBanCauTraLoiChanging(value);
					this.SendPropertyChanging();
					this._NguoiXuatBanCauTraLoi = value;
					this.SendPropertyChanged("NguoiXuatBanCauTraLoi");
					this.OnNguoiXuatBanCauTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuatBanCauTraLoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXuatBanCauTraLoi
		{
			get
			{
				return this._NgayXuatBanCauTraLoi;
			}
			set
			{
				if ((this._NgayXuatBanCauTraLoi != value))
				{
					this.OnNgayXuatBanCauTraLoiChanging(value);
					this.SendPropertyChanging();
					this._NgayXuatBanCauTraLoi = value;
					this.SendPropertyChanged("NgayXuatBanCauTraLoi");
					this.OnNgayXuatBanCauTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TiepNhanCauHoi", DbType="Bit")]
		public System.Nullable<bool> TiepNhanCauHoi
		{
			get
			{
				return this._TiepNhanCauHoi;
			}
			set
			{
				if ((this._TiepNhanCauHoi != value))
				{
					this.OnTiepNhanCauHoiChanging(value);
					this.SendPropertyChanging();
					this._TiepNhanCauHoi = value;
					this.SendPropertyChanged("TiepNhanCauHoi");
					this.OnTiepNhanCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTS", DbType="NVarChar(MAX)")]
		public string FTS
		{
			get
			{
				return this._FTS;
			}
			set
			{
				if ((this._FTS != value))
				{
					this.OnFTSChanging(value);
					this.SendPropertyChanging();
					this._FTS = value;
					this.SendPropertyChanged("FTS");
					this.OnFTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhongPheDuyetTraLoi", DbType="Bit")]
		public System.Nullable<bool> KhongPheDuyetTraLoi
		{
			get
			{
				return this._KhongPheDuyetTraLoi;
			}
			set
			{
				if ((this._KhongPheDuyetTraLoi != value))
				{
					this.OnKhongPheDuyetTraLoiChanging(value);
					this.SendPropertyChanging();
					this._KhongPheDuyetTraLoi = value;
					this.SendPropertyChanged("KhongPheDuyetTraLoi");
					this.OnKhongPheDuyetTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongBanID", DbType="Int")]
		public System.Nullable<int> PhongBanID
		{
			get
			{
				return this._PhongBanID;
			}
			set
			{
				if ((this._PhongBanID != value))
				{
					this.OnPhongBanIDChanging(value);
					this.SendPropertyChanging();
					this._PhongBanID = value;
					this.SendPropertyChanged("PhongBanID");
					this.OnPhongBanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuyetThongBao", DbType="Bit")]
		public System.Nullable<bool> DuyetThongBao
		{
			get
			{
				return this._DuyetThongBao;
			}
			set
			{
				if ((this._DuyetThongBao != value))
				{
					this.OnDuyetThongBaoChanging(value);
					this.SendPropertyChanging();
					this._DuyetThongBao = value;
					this.SendPropertyChanged("DuyetThongBao");
					this.OnDuyetThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDuyetThongBao", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiDuyetThongBao
		{
			get
			{
				return this._NguoiDuyetThongBao;
			}
			set
			{
				if ((this._NguoiDuyetThongBao != value))
				{
					this.OnNguoiDuyetThongBaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiDuyetThongBao = value;
					this.SendPropertyChanged("NguoiDuyetThongBao");
					this.OnNguoiDuyetThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuyetThongBao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDuyetThongBao
		{
			get
			{
				return this._NgayDuyetThongBao;
			}
			set
			{
				if ((this._NgayDuyetThongBao != value))
				{
					this.OnNgayDuyetThongBaoChanging(value);
					this.SendPropertyChanging();
					this._NgayDuyetThongBao = value;
					this.SendPropertyChanged("NgayDuyetThongBao");
					this.OnNgayDuyetThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XuatBanThongBao", DbType="Bit")]
		public System.Nullable<bool> XuatBanThongBao
		{
			get
			{
				return this._XuatBanThongBao;
			}
			set
			{
				if ((this._XuatBanThongBao != value))
				{
					this.OnXuatBanThongBaoChanging(value);
					this.SendPropertyChanging();
					this._XuatBanThongBao = value;
					this.SendPropertyChanged("XuatBanThongBao");
					this.OnXuatBanThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiXuatBanThongBao", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiXuatBanThongBao
		{
			get
			{
				return this._NguoiXuatBanThongBao;
			}
			set
			{
				if ((this._NguoiXuatBanThongBao != value))
				{
					this.OnNguoiXuatBanThongBaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiXuatBanThongBao = value;
					this.SendPropertyChanged("NguoiXuatBanThongBao");
					this.OnNguoiXuatBanThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuatBanThongBao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXuatBanThongBao
		{
			get
			{
				return this._NgayXuatBanThongBao;
			}
			set
			{
				if ((this._NgayXuatBanThongBao != value))
				{
					this.OnNgayXuatBanThongBaoChanging(value);
					this.SendPropertyChanging();
					this._NgayXuatBanThongBao = value;
					this.SendPropertyChanged("NgayXuatBanThongBao");
					this.OnNgayXuatBanThongBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatQuestionByUser", DbType="Int")]
		public System.Nullable<int> CreatQuestionByUser
		{
			get
			{
				return this._CreatQuestionByUser;
			}
			set
			{
				if ((this._CreatQuestionByUser != value))
				{
					this.OnCreatQuestionByUserChanging(value);
					this.SendPropertyChanging();
					this._CreatQuestionByUser = value;
					this.SendPropertyChanged("CreatQuestionByUser");
					this.OnCreatQuestionByUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTiepNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTiepNhan
		{
			get
			{
				return this._NgayTiepNhan;
			}
			set
			{
				if ((this._NgayTiepNhan != value))
				{
					this.OnNgayTiepNhanChanging(value);
					this.SendPropertyChanging();
					this._NgayTiepNhan = value;
					this.SendPropertyChanged("NgayTiepNhan");
					this.OnNgayTiepNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTiepNhan", DbType="Int")]
		public System.Nullable<int> NguoiTiepNhan
		{
			get
			{
				return this._NguoiTiepNhan;
			}
			set
			{
				if ((this._NguoiTiepNhan != value))
				{
					this.OnNguoiTiepNhanChanging(value);
					this.SendPropertyChanging();
					this._NguoiTiepNhan = value;
					this.SendPropertyChanged("NguoiTiepNhan");
					this.OnNguoiTiepNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusSend", DbType="Bit")]
		public System.Nullable<bool> StatusSend
		{
			get
			{
				return this._StatusSend;
			}
			set
			{
				if ((this._StatusSend != value))
				{
					this.OnStatusSendChanging(value);
					this.SendPropertyChanging();
					this._StatusSend = value;
					this.SendPropertyChanged("StatusSend");
					this.OnStatusSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenDuThao", DbType="Bit")]
		public System.Nullable<bool> ChuyenDuThao
		{
			get
			{
				return this._ChuyenDuThao;
			}
			set
			{
				if ((this._ChuyenDuThao != value))
				{
					this.OnChuyenDuThaoChanging(value);
					this.SendPropertyChanging();
					this._ChuyenDuThao = value;
					this.SendPropertyChanged("ChuyenDuThao");
					this.OnChuyenDuThaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiChuyenDuThao", DbType="Int")]
		public System.Nullable<int> NguoiChuyenDuThao
		{
			get
			{
				return this._NguoiChuyenDuThao;
			}
			set
			{
				if ((this._NguoiChuyenDuThao != value))
				{
					this.OnNguoiChuyenDuThaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiChuyenDuThao = value;
					this.SendPropertyChanged("NguoiChuyenDuThao");
					this.OnNguoiChuyenDuThaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyenDuThao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyenDuThao
		{
			get
			{
				return this._NgayChuyenDuThao;
			}
			set
			{
				if ((this._NgayChuyenDuThao != value))
				{
					this.OnNgayChuyenDuThaoChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenDuThao = value;
					this.SendPropertyChanged("NgayChuyenDuThao");
					this.OnNgayChuyenDuThaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID")]
		public int SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
