// <auto-generated />
namespace mojoPortal.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addtbldata2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtbldata2));
        
        string IMigrationMetadata.Id
        {
            get { return "202307030338152_add-tbl-data2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
