// <auto-generated />
namespace mojoPortal.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetblcore_SettingSSO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetblcore_SettingSSO));
        
        string IMigrationMetadata.Id
        {
            get { return "202308261138170_update-tbl-core_SettingSSO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
