//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoIntroduceFeature.UI
{


    public partial class ViewList
    {

        /// <summary>
        /// pnlOuterWrap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.UI.OuterWrapperPanel pnlOuterWrap;

        /// <summary>
        /// CornerRounderTop1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.Controls.CornerRounderTop CornerRounderTop1;

        /// <summary>
        /// pnlInnerWrap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.UI.InnerWrapperPanel pnlInnerWrap;

        /// <summary>
        /// heading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.UI.HeadingControl heading;

        /// <summary>
        /// pnlOuterBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.UI.OuterBodyPanel pnlOuterBody;

        /// <summary>
        /// pnlInnerBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.UI.InnerBodyPanel pnlInnerBody;

        /// <summary>
        /// VideoListControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VideoIntroduceFeature.UI.VideoListControl VideoListControl;

        /// <summary>
        /// divCleared control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.UI.EmptyPanel divCleared;

        /// <summary>
        /// CornerRounderBottom1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.Controls.CornerRounderBottom CornerRounderBottom1;

        /// <summary>
        /// ka1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mojoPortal.Web.UI.SessionKeepAliveControl ka1;
    }
}
